### ISSUE TITLE
Broken order and colors after following the link

### ISSUE THREAD

**Issue by DenisMkS** [ckabalan/visualsubnetcalc#22]
I split networks and clicked "Copy Shareable URL". After following this link subnets appear in a wrong order.
Original:
<img width="1747" alt="image" src="https://github.com/user-attachments/assets/67cb308d-149c-48d1-bf52-ec21beb2c361">
After following the link (GCP and On-Premise should be at the very bottom):
<img width="1765" alt="image" src="https://github.com/user-attachments/assets/ef09517c-7e49-4537-85bc-fc21bdfba22e">

Here is the [link](https://visualsubnetcalc.com/index.html?c=1N4IgbiBcIEwgNCARlEBGADAOm7g9ABwIgC2qAggFoCqASgKLEDOUoGRkoaAnK7AIZ8AdqgDiAYQAKAAloBTJnIBOYOQBMQAX0QBmQZxAjoAeSEBaAA5K5JAJaLZC5ao2btIDLwMZ9bFN4BjPgwNbzlggDNhCgB1AGVpOQBXMwB3BQAXMzRpNTkIdzQogyMQcnjElPSmLJyrAHtXQvCDGGLQUvKE5LTM7Oka-gBzWyEh4iDoLV12kAA2cZLY7qq+nKYAC35rV0QAdkWO5cremv7RiKVBNzdENFCj6C6ToXqlDI3srULJ0BgHwzHHoBORCDJXAA2X3cOgBnQqSSYpyycEQkxA30K-j+vxAABY4cdEWY5PwzmhpiAAKyEp4VeSKFTqb66XFzWllelOJm7EB7DnPBnOZk3Qq+WDY-G4ggCgBeSWs0nEoPB-Ah0mocUp3DlCrk0noZIyGq1t2puMwusVomUJH4QgAntIYpklSrIZS0Pdok95YqAHJvD4GhX1CzhG66SVzC3-H1lP36l01ENKMMRu6w+PkROORkuFl8i0E7O5oU8z000t6vPCpqitxAA)

One more issue. Colors are broken: [link](https://visualsubnetcalc.com/index.html?c=1N4IgbiBcIEwgNCARlEBGADAOm7g9ABwIgC2qAggFoCqASgKLEDOUoGRkoaAnK7AIZ8AdqgDiAYQAKAAloBTJnIBOYOQBNiAY1QBiOQDYDBkAF9EAZkGcQI6AHkhAWgAOSuSQCWi2QuWqNiNrQeoahpmYgGLzWGFZsKDFBbBoxcnwYAGbCFADqAMrScgCujgDuCgAujmjSanIQgboZGWr6-ACspohoWda2IOT5hSXlTFU1rgD2ASBBIDrNrR3h3WnWML2g-YMFxWWV1dJj-ADmHkInWk0tbZ0R5psg+pd9ubsjBzVMABb8bjNzBY3ZYRADsLy2b2G+zGh3OGSUgkawUWt3CJgiaBSkOgO2hQkmSgq32qVxRwLumKSsGxNihe00ciEFURABtScj5qiQRZadshkUmDCqnBOUClpTMQlQDBqQAWPlQwWOOT8WFoMlcildEDtRW4obyRQqdSa8VojEWan6fUDQ2+E0A64SnWg214o1+U0Yy3oOKwaUgOXUgjugBeRTc0nETJZ-FZ0moeTN-AwmjlzR13HDkbk0noaoqieTYtT6czvva1MwOajomUJH4QgAntIcpVo7G2Sm0xmspisdlcRGowA5QnE-ORybONKl3sV33mQP6aswWt59tjKdKGdz2a6Mt9nVocwbnzG-w98v9sHVhVDgYjvOex3X4+YvWP8jPi9ep3BEei4+j6QA)

### Steps to reproduce:
1. Split subnets as shown
<img width="893" alt="image" src="https://github.com/user-attachments/assets/5201eb46-34e0-4d27-b9c4-3957c68aefa0">
2. Copy link
3. Open copied link in a new tab

**Comment by ckabalan** [comment]
Hi, apologies for not seeing this until now. I've been dealing with holidays and family surgeries/sickness.

Regardless, wow, this is a major issue and I'm not sure how this got missed. It's definitely nuanced because at first glance it seems to work properly when I just randomly split and click things. HOWEVER, I was able to reproduce your issue with concerning results.

There is a silver lining, and that this is purely formatting/rendering issue. When reproduce your split view and copy the link, it renders improperly but the import/export portion from that improperly rendered page looks like it has the correct data except the dictionary (which shouldn't need to be ordered) is out of order. This means that no data is lost for anyone creating links and sharing them, and when I fix the rendering piece no one will be the wiser.

Stay tuned.

**Comment by ckabalan** [comment]
@DenisMkS - Thanks so much for this report, it's been resolved and release to live (v1.3.1). I'm not sure how this hasn't been surfaced earlier since this must have been an edge case since v1.0.

Your links should now work properly. If they don't you may need to clear your cache, try incognito or another browser.

**Comment by DenisMkS** [comment]
Thank you @ckabalan !
